[package]
name = "autost"
version = "0.1.0"
edition = "2021"

[dependencies]
ammonia = "4.0.0"
askama = "0.12.1"
comrak = "0.28.0"
html5ever = "0.27.0"
jane-eyre = "0.3.0"
markup5ever_rcdom = "0.3.0"
